# Generated by Django 3.1.4 on 2021-04-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('identifier', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('day_high', models.DecimalField(decimal_places=3, max_digits=8)),
                ('day_low', models.DecimalField(decimal_places=3, max_digits=8)),
                ('current', models.DecimalField(decimal_places=3, max_digits=8)),
                ('change', models.DecimalField(decimal_places=2, max_digits=4)),
                ('pchange', models.DecimalField(decimal_places=2, max_digits=3)),
                ('pchange365', models.DecimalField(decimal_places=2, max_digits=5)),
                ('last_update', models.DateTimeField()),
            ],
            options={
                'ordering': ['identifier'],
            },
        ),
    ]
