# Generated by Django 3.1.4 on 2021-04-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_remove_stock_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='change',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='current',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='day_high',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='day_low',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='pchange',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='pchange365',
            field=models.FloatField(),
        ),
    ]
