# Generated by Django 3.1.4 on 2021-04-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_auto_20210428_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
