# Generated by Django 3.1.4 on 2021-05-01 23:10

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_auto_20210501_1833'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='stock',
            managers=[
                ('newmanager', django.db.models.manager.Manager()),
            ],
        ),
    ]
